# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_comment', '0003_auto_20170702_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
