# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170507_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点击次数'),
        ),
    ]
