# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170515_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(max_length=200, verbose_name='文章摘要'),
        ),
    ]
