# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
