# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 10:15
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.png', storage=django.core.files.storage.FileSystemStorage(location='media/avatar'), upload_to=''),
        ),
    ]
